
select * from customer


--Q1. What is the total Revenue generated by male vs. female customers?
SELECT "Gender", SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";


--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT "Customer ID",
       "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes'
  AND "Purchase Amount (USD)" >= (
        SELECT AVG("Purchase Amount (USD)")
        FROM customer
      );


--Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    "Item Purchased",
    ROUND(AVG(("Review Rating")::numeric), 2) AS "AVG Product Rating"
FROM customer
GROUP BY "Item Purchased"
ORDER BY AVG(("Review Rating")::numeric) DESC
LIMIT 5;





--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    "Shipping Type",
    ROUND(AVG(("Purchase Amount (USD)")::numeric), 2) AS "Average Purchase (USD)"
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type"
ORDER BY "Average Purchase (USD)" DESC;





--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
    "Subscription Status",
    COUNT(DISTINCT "Customer ID") AS "Total Customers",
    ROUND(AVG(("Purchase Amount (USD)")::numeric), 2) AS "Average Spend (USD)",
    SUM(("Purchase Amount (USD)")::numeric) AS "Total Revenue (USD)"
FROM customer
GROUP BY "Subscription Status"
ORDER BY "Total Revenue (USD)" DESC;





--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    "Item Purchased",
    ROUND(
        (SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END)::numeric / COUNT(*) * 100),
        2
    ) AS "Discount Percentage"
FROM customer
GROUP BY "Item Purchased"
ORDER BY "Discount Percentage" DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total
--number ofprevious purchases, and show the count of each segment. 

SELECT 
    CASE
        WHEN "Previous Purchases" = 1 THEN 'New'
        WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS "Customer Segment",
    COUNT(DISTINCT "Customer ID") AS "Total Customers"
FROM customer
GROUP BY "Customer Segment"
ORDER BY "Total Customers" DESC;

--Q8. What are the top 3 most purchased products within each category?
SELECT 
    "Category",
    "Item Purchased",
    "Total Purchases",
    "Item Rank"
FROM (
    SELECT 
        "Category",
        "Item Purchased",
        COUNT(*) AS "Total Purchases",
        RANK() OVER (PARTITION BY "Category" ORDER BY COUNT(*) DESC) AS "Item Rank"
    FROM customer
    GROUP BY "Category", "Item Purchased"
) AS ranked
WHERE "Item Rank" <= 3
ORDER BY "Category", "Item Rank";



--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    CASE 
        WHEN "Previous Purchases" > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS "Customer Type",
    "Subscription Status",
    COUNT(DISTINCT "Customer ID") AS "Total Customers"
FROM customer
GROUP BY "Customer Type", "Subscription Status"
ORDER BY "Customer Type", "Subscription Status";

--Q10. What is the revenue contribution of each age group? 
SELECT 
  CASE 
    WHEN "Age" < 25 THEN 'Young Adult'
    WHEN "Age" BETWEEN 25 AND 39 THEN 'Adult'
    WHEN "Age" BETWEEN 40 AND 59 THEN 'Middle Aged'
    ELSE 'Senior'
  END AS "Age Group",
  SUM(("Purchase Amount (USD)")::numeric) AS "Total Revenue"
FROM customer
GROUP BY 1
ORDER BY "Total Revenue" DESC;


